using '../main.bicep'

param environment = 'dev'
param project = 'energybot'
param openAiAccountName = 'aoai-energybot-dev'
param storageAccountName = 'stragenergybotdev'
param funcStorageAccountName = 'stfuncenergybotdev'
param containerName = 'documents'
param gptDeploymentName = 'gpt-4o'
param embeddingDeploymentName = 'text-embedding-3-small'
param functionAppName = 'func-energybot-dev'
param appServicePlanName = 'asp-energybot-dev'
param fileShareName = 'chroma-index'
